function templates = CreateDartelTemplate12(volumenes, prefix)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% CreateDartelTemplate
%--------------------------------------------------------------------------
% 
% Executed the DARTEL(create template) task in SPM8.
%
%__________________________________________________________________________
% INPUTS:
%  - volumenes: a cell array with the path to all subject.
%  - prefix: a string to name new files.
%     
% OUTPUTS:
%  - templates: a cell array with the path to the templates created.
%
%__________________________________________________________________________
%
% Author: Laura Nunez Gonzalez
% URJC - 08 / March / 2016
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
try,
        %% Generated by nipype.interfaces.spm
        if isempty(which('spm')),
             throw(MException('SPMCheck:NotFound', 'SPM not in matlab path'));
        end
        [name, version] = spm('ver');
        fprintf('SPM version: %s Release: %s\n',name, version);
        fprintf('SPM path: %s\n', which('spm'));
        spm('Defaults','fMRI');

        if strcmp(name, 'SPM8') || strcmp(name(1:5), 'SPM12'),
           spm_jobman('initcfg');
           spm_get_defaults('cmdline', 1);
        end

%%      Tarea de spm a ejecutar 

        matlabbatch{1}.spm.tools.dartel.warp.images = volumenes;
        matlabbatch{1}.spm.tools.dartel.warp.settings.template = prefix;
        matlabbatch{1}.spm.tools.dartel.warp.settings.rform = 0;
        matlabbatch{1}.spm.tools.dartel.warp.settings.param(1).its = 3;
        matlabbatch{1}.spm.tools.dartel.warp.settings.param(1).rparam = [4 2 1e-06];
        matlabbatch{1}.spm.tools.dartel.warp.settings.param(1).K = 0;
        matlabbatch{1}.spm.tools.dartel.warp.settings.param(1).slam = 16;
        matlabbatch{1}.spm.tools.dartel.warp.settings.param(2).its = 3;
        matlabbatch{1}.spm.tools.dartel.warp.settings.param(2).rparam = [2 1 1e-06];
        matlabbatch{1}.spm.tools.dartel.warp.settings.param(2).K = 0;
        matlabbatch{1}.spm.tools.dartel.warp.settings.param(2).slam = 8;
        matlabbatch{1}.spm.tools.dartel.warp.settings.param(3).its = 3;
        matlabbatch{1}.spm.tools.dartel.warp.settings.param(3).rparam = [1 0.5 1e-06];
        matlabbatch{1}.spm.tools.dartel.warp.settings.param(3).K = 1;
        matlabbatch{1}.spm.tools.dartel.warp.settings.param(3).slam = 4;
        matlabbatch{1}.spm.tools.dartel.warp.settings.param(4).its = 3;
        matlabbatch{1}.spm.tools.dartel.warp.settings.param(4).rparam = [0.5 0.25 1e-06];
        matlabbatch{1}.spm.tools.dartel.warp.settings.param(4).K = 2;
        matlabbatch{1}.spm.tools.dartel.warp.settings.param(4).slam = 2;
        matlabbatch{1}.spm.tools.dartel.warp.settings.param(5).its = 3;
        matlabbatch{1}.spm.tools.dartel.warp.settings.param(5).rparam = [0.25 0.125 1e-06];
        matlabbatch{1}.spm.tools.dartel.warp.settings.param(5).K = 4;
        matlabbatch{1}.spm.tools.dartel.warp.settings.param(5).slam = 1;
        matlabbatch{1}.spm.tools.dartel.warp.settings.param(6).its = 3;
        matlabbatch{1}.spm.tools.dartel.warp.settings.param(6).rparam = [0.25 0.125 1e-06];
        matlabbatch{1}.spm.tools.dartel.warp.settings.param(6).K = 6;
        matlabbatch{1}.spm.tools.dartel.warp.settings.param(6).slam = 0.5;
        matlabbatch{1}.spm.tools.dartel.warp.settings.optim.lmreg = 0.01;
        matlabbatch{1}.spm.tools.dartel.warp.settings.optim.cyc = 3;
        matlabbatch{1}.spm.tools.dartel.warp.settings.optim.its = 3;


        spm_jobman('run', matlabbatch);

        
        if strcmp(name, 'SPM8') || strcmp(name(1:5), 'SPM12'),
            close('all', 'force');
        end;
        
%%      Recoleccion de los resultados
        dirvol = dir(volumenes{1}{1});
        name = dirvol.name;
        path = strrep(volumenes{1}{1},name,'');
        
        templates = {[path prefix '_1.nii'] [path prefix '_2.nii'] [path prefix '_3.nii'] [path prefix '_4.nii'] [path prefix '_5.nii'] [path prefix '_6.nii']};
            
,catch ME,
fprintf(2,'MATLAB code threw an exception:\n');
fprintf(2,'%s\n',ME.message);
if length(ME.stack) ~= 0, fprintf(2,'File:%s\nName:%s\nLine:%d\n',ME.stack.file,ME.stack.name,ME.stack.line);, end;
end;
