close all
clear all
clc
PrepareData12('/Volumes/LaCie/DATOS_OLFATO_HELENA_AMATOMIA/MUJERES','/Volumes/LaCie/DATOS_OLFATO_HELENA_AMATOMIA/MUJERES_PREPARED');
PrepareData12('/Volumes/LaCie/DATOS_OLFATO_HELENA_AMATOMIA/HOMBRES','/Volumes/LaCie/DATOS_OLFATO_HELENA_AMATOMIA/HOMBRES_PREPARED');
