function files = Normalise12(images,flowfields, template)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Normalize
%--------------------------------------------------------------------------
% 
% Executed the 'Normalise to MNI Space' task in SPM8.
%
%__________________________________________________________________________
% INPUTS:
%  - images: a cell array with the path to all subject.
%  - flowfields: a cell array with the path to the flowfields files.
%  - templates:a cell array with the path to the templates.
%     
% OUTPUTS:
%  - files: cell array with the path to the normalised files.
%
%__________________________________________________________________________
%
% Author: Laura Nunez Gonzalez
% URJC - 08 / March / 2016
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
try,
        %% Generated by nipype.interfaces.spm
        if isempty(which('spm')),
             throw(MException('SPMCheck:NotFound', 'SPM not in matlab path'));
        end
        [name, version] = spm('ver');
        fprintf('SPM version: %s Release: %s\n',name, version);
        fprintf('SPM path: %s\n', which('spm'));
        spm('Defaults','fMRI');

        if strcmp(name, 'SPM8') || strcmp(name(1:5), 'SPM12'),
           spm_jobman('initcfg');
           spm_get_defaults('cmdline', 1);
        end



%%      Tarea de spm a ejecutar 
        matlabbatch{1}.spm.tools.dartel.mni_norm.template = {template};
        matlabbatch{1}.spm.tools.dartel.mni_norm.data.subjs.flowfields = flowfields;
        matlabbatch{1}.spm.tools.dartel.mni_norm.data.subjs.images = images';

        matlabbatch{1}.spm.tools.dartel.mni_norm.vox = [1.5 1.5 1.5];
        matlabbatch{1}.spm.tools.dartel.mni_norm.bb = [NaN NaN NaN
                                                       NaN NaN NaN];
        matlabbatch{1}.spm.tools.dartel.mni_norm.preserve = 1;
        matlabbatch{1}.spm.tools.dartel.mni_norm.fwhm = [8 8 8];
       

        spm_jobman('run', matlabbatch);

        
        if strcmp(name, 'SPM8') || strcmp(name(1:5), 'SPM12'),
            close('all', 'force');
        end;
            
        
        
%%      Recoleccion de los resultados
        
        files = {};
        for i=1:length(images)
            normalized_files = {}; 
            try
                for j=1:length(images{i})
               
                    dirvol = dir(images{i}{j});
                    name = dirvol.name;
                    dirDatos = strrep(images{i}{j},name,'');
                    normalized = [dirDatos 'smw' name];
                    normalized_files{j}= normalized;
                end;
                files{i} = normalized_files;
            catch ME
            end;
        end;
        
        
,catch ME,
fprintf(2,'MATLAB code threw an exception:\n');
fprintf(2,'%s\n',ME.message);
if length(ME.stack) ~= 0, 
    fprintf(2,'File:%s\nName:%s\nLine:%d\n',ME.stack.file,ME.stack.name,ME.stack.line);, 
end;
end;
